<section class="panier relative  w-[355px] md:w-[455px] h-screen flex flex-col justify-center items-center p-15 gap-20  rounded-10">
    <div class="head flex flex-col justify-center py-30">
        <img class="img" src="src/assets/svg/panier/panier.svg" alt="panier">
        <p class="title text-28 font-700">Votre panier est vide...</p>
    </div>

    <div class="panier-pub flex flex-row w-full justify-between items-center bg-panier-very-light-red rounded-5">
        <img class="icon w-[51px] h-[51px] ml-5" src="src/assets/panier/promotion.png">
        <div class="content gap-20 w-fit h-full flex flex-col py-20">
            <div class="text w-fit">
                <p class="label text-20 font-600">Profitez de toutes</p>
                <p class="label text-16 font-600 text-panier-red-text">nos promos</p>
            </div>
            <a href="#" class="btn-red">J’en profite</a>
        </div>
        <img class="illustration w-[66px] h-[103px] self-end rounded-br-5" src="src/assets/panier/illus1.webp" alt="illustration">
    </div>
    
    <div class="panier-pub flex flex-row w-full justify-between items-center bg-panier-very-light-yellow rounded-5">
        <img class="icon w-[51px] h-[51px] ml-5" src="src/assets/panier/anti-inflation.webp">
        <div class="content gap-20 w-fit h-full flex flex-col py-20">
            <div class="text w-fit">
                <p class="label text-20 font-600">Nos essentiels à</p>
                <p class="label text-16 font-600 text-panier-red-text">petits prix</p>
            </div>
            <a href="#" class="btn-red">Je fonce</a>
        </div>
        <img class="illustration w-[66px] h-[103px] self-end rounded-br-5" src="src/assets/panier/illus2.webp" alt="illustration">
    </div>  
</section>