<section class="footer-bas w-screen md:px-70 md:pb-30 pt-10 mx-auto">
    <div class="layout flex flex-col md:flex-row md:justify-between p-30 gap-15 md:gap-0 md:border-y md:border-accueil-grey">
        <div class="footer-bottom-section">
            <p class="footer-title">Paiement 100% sécurisé</p>
            <div class="cards flex flex-col md:flex-row gap-10">
                <div class="icons flex flex-row items-center gap-11">
                    <img class="footer-icon" src="src/assets/svg/footer/cb.svg" alt="cb">
                    <img class="footer-icon" src="src/assets/svg/footer/visa.svg" alt="visa">
                    <img class="footer-icon" src="src/assets/svg/footer/mastercard.svg" alt="mastercard">
                    <img class="footer-icon" src="src/assets/svg/footer/american.svg" alt="american">
                    <img class="footer-icon" src="src/assets/svg/footer/pass.svg" alt="pass">
                    <img class="footer-icon" src="src/assets/svg/footer/paypal.svg" alt="paypal">
                    <img class="footer-icon-tall" src="src/assets/svg/footer/carrefour-plus.webp" alt="plus">
                    <img class="footer-icon-tall" src="src/assets/svg/footer/everywish.webp" alt="everywish">
                </div>
                <a href="#" class="btn text-nav-blue hover:text-nav-blue-hover underline">En savoir plus</a>   
            </div>
        </div>    
        <div class="footer-bottom-section">
            <p class="footer-title">Options d’accessibilité</p>
            <img class="faciliti-icon w-[85px] h-[26px]" src="src/assets/svg/profil/faciliti.webp" alt="faciliti">
        </div>

        <div class="footer-bottom-section">
            <p class="footer-title">Nous suivre</p>
            <div class="media-icons flex flex-row gap-10">
                <img class="media-icon" src="src/assets/svg/footer/facebook.svg" alt="facebook">
                <img class="media-icon" src="src/assets/svg/footer/instagram.svg" alt="instagram">
                <img class="media-icon" src="src/assets/svg/footer/twitter.svg" alt="twitter">
                <img class="media-icon" src="src/assets/svg/footer/youtube.svg" alt="youtube">
                <img class="media-icon" src="src/assets/svg/footer/tiktok.svg" alt="tiktok">
            </div>
        </div>
    </div>    
</section>