<section class="categorieavantages w-screen h-fit flex flex-col md:flex-row px-20 py-10 gap-27 md:gap-13 md:justify-center items-stretch">

    <div class="categorie-card">
        <div class="categorie-head">
            <img class="categorie-img" src="src/assets/categorieavantages/carte.webp" alt="carte">
            <p class="categorie-title hidden md:block">Ma carte Carrefour</p>
        </div>
        <div class="categorie-text">
            <p class="categorie-title md:hidden">Ma carte Carrefour</p>
            <p class="categorie-label">Carte fidélité</p>
            <p class="categorie-label">Créer ma carte</p>
            <p class="categorie-label">Clubs de sport</p>
        </div>
    </div>

    <div class="categorie-card">
        <div class="categorie-head">
            <img class="categorie-img" src="src/assets/categorieavantages/banque-assurances.webp" alt="banque-assurances">
            <p class="categorie-title hidden md:block">Banque et assurances</p>
        </div>
        <div class="categorie-text">
            <p class="categorie-title md:hidden">Banque et assurances</p>
            <p class="categorie-label">Carte Pass</p>
            <p class="categorie-label">Crédit</p>
            <p class="categorie-label">Assurances</p>
            <p class="categorie-label">Garanties Carrefour +</p>
        </div>
    </div>

    <div class="categorie-card">
        <div class="categorie-head">
            <img class="categorie-img" src="src/assets/categorieavantages/energies.webp" alt="carte">
            <p class="categorie-title hidden md:block">Energies</p>
        </div>
        <div class="categorie-text">
            <p class="categorie-title md:hidden">Energies</p>
            <p class="categorie-label">Fioul domestique</p>
            <p class="categorie-label">Gaz en bouteilles</p>
            <p class="categorie-label">Prime Eco Travaux</p>
            <p class="categorie-label">Energies vertes</p>
        </div>
    </div>

    <div class="categorie-card">
        <div class="categorie-head">
            <img class="categorie-img" src="src/assets/categorieavantages/loisirs.webp" alt="carte">
            <p class="categorie-title hidden md:block">Loisirs</p>
        </div>
        <div class="categorie-text">
            <p class="categorie-title md:hidden">Loisirs</p>
            <p class="categorie-label">Location de voitures</p>
            <p class="categorie-label">Location utilitaires</p>
            <p class="categorie-label">Offre eSim</p>
            <p class="categorie-label">Spectacles</p>
        </div>
    </div>
</section>