<section class="bienvenue w-screen px-20 md:px-60 py-20 font-sans">
    <div class="layout flex flex-col justify-center w-full gap-30">

        <p class="head-title text-nav-blue text-36 font-400">Bienvenue chez Carrefour</p>

        <div class="cards flex md:flex-row flex-col justify-center items-stretch w-full h-fit gap-30">

            <div class="card flex flex-row items-start md:items-center justify-between w-fit h-full p-30 border border-accueil-grey rounded-10 shadow-card">
                <div class="info flex flex-col justify-between h-full">    
                    <div class="text flex-grow mb-10">
                        <p class="title text-20 font-800">Courses du quotidien</p>
                        <p class="description text-18 font-600">Retrait gratuit en drive ou livrées chez vous en 1h</p>
                    </div>    
                    <a class="btn-blue w-fit" href="#">Faire mes courses</a>   
                </div>
                <img class="img md:w-[181px] w-[90px] h-auto" src="src/assets/bienvenue/courses.webp" alt="courses">
            </div>
    
            <div class="card flex flex-row items-start md:items-center justify-between w-fit h-full p-30 border border-accueil-grey rounded-10 shadow-card">
                <div class="info flex flex-col justify-between h-full">    
                    <div class="text flex-grow">
                        <p class="title text-20 font-800">Maison & loisirs</p>
                        <p class="description text-18 font-600">Retrait magasin gratuit, livraison gratuite</p>
                        <p class="description text-18 font-700">dès 60$ d’achat</p>
                    </div>    
                    <a class="btn-blue w-fit" href="#">Découvrir</a>   
                </div>
                <img class="img md:w-[181px] w-[90px] h-auto" src="src/assets/bienvenue/loisirs.webp" alt="courses">
            </div>

        </div>

    </div>
</section>