<section class="profil w-[220px] p-10 rounded-10 shadow-card">
    <div class="boutons-compte flex flex-col justify-center items-center py-10 border-b border-panier-grey">
        <a class="btn-blue">Me connecter</a>
        <a class="btn-white">Créer mon compte</a>
    </div>

    <div class="boutons-infos flex flex-col justify-center gap-10 py-10 border-b border-panier-grey place-items-center">
        <a href="#" class="btn-black"><img class="icon" src="src/assets/svg/profil/compte.svg">Mon compte</a>
        <a href="#" class="btn-black"><img class="icon" src="src/assets/svg/profil/achats.svg">Mes achats</a>
        <a href="#" class="btn-black"><img class="icon" src="src/assets/svg/profil/avantages.svg">Mes avantages fidélités</a>
        <a href="#" class="btn-black"><img class="icon" src="src/assets/svg/profil/infos.svg">Mes infos personnelles</a> 
        <a href="#" class="btn"><img src="src/assets/svg/profil/faciliti.webp"></a>
    </div>
    <a href="#" class="btn-black py-10">Ma communauté</a>
</section>