

<section class="actualité flex flex-row justify-between px-39 py-9 gap-2 pointer-events-auto" data-filter="{{category}}" value="{{id}}">
    <div class="flex flex-row items-center gap-6" data-filter="{{category}}" value="{{id}}">
        <img class="icon w-23 md:w-10 rounded-30" src="src/assets/icons/menu/{{image}}" alt="icon" data-filter="{{category}}" value="{{id}}">
        <p class="text" data-filter="{{category}}" value="{{id}}">{{name}}</p>
    </div>
</section>