<section class="achatsmagasin font-sans w-sceen h-fit py-10">
    <div class="layout flex flex-col justify-center items-center gap-25">
        <p class="title text-28 font-700">Vos achats en magasin</p>
        <div class="images flex flex-col md:flex-row gap-10 md:gap-30">
            <img class="img w-[262px] md:w-[417px] h-auto" src="src/assets/achatsmagasin/magasin.webp" alt="magasin">
            <img class="img w-[262px] md:w-[417px] h-auto" src="src/assets/achatsmagasin/economies.webp" alt="economies">
            <img class="img w-[262px] md:w-[417px] h-auto" src="src/assets/achatsmagasin/bons-plans.webp" alt="bons plans">
        </div>
    </div>
</section>