<section class="actualites w-screen">
    <div class="layout flex overflow-hidden snap-x snap-mandatory md:flex-row justify-center gap-50">
        <img class="img w-309 rounded-5 snap-center" src="src/assets/actualites/grand-jeu.webp" alt="Grand jeu">
        <img class="img w-309 rounded-5 snap-center" src="src/assets/actualites/marque-preferee.webp" alt="Marque preferee">
        <img class="img w-309 rounded-5 snap-center" src="src/assets/actualites/pas-manquer.webp" alt="Pas manquer">
    </div>    
</section>