<div class="menu flex flex-row w-fit h-full font-sans">
    <div class="categories flex flex-col flex-center bg-menu-background-light">
        <div class="category flex flex-col items-center px-15 py-13">
            <img class="w-77 h-77 rounded-50" src="src/assets/categories/courses.webp" alt="Courses">
            <span class="block">Courses du quotidien</span>
        </div>
        <div class="category flex flex-col items-center px-15 py-13">
            <img class="w-77 h-77 rounded-50" src="src/assets/categories/decorations.webp" alt="Décorations">
            <span>Décorations</span>
        </div>
        <div class="category flex flex-col items-center px-15 py-13">
            <img class="w-77 h-77 rounded-50" src="src/assets/categories/outils.webp" alt="Outils">
            <span>Outils</span>
        </div>
        <div class="category flex flex-col items-center px-15 py-13">
            <img class="w-77 h-77 rounded-50" src="src/assets/categories/entretien.webp" alt="Entretien">
            <span>Entretien</span>
        </div>
        <div class="category flex flex-col items-center px-15 py-13">
            <img class="w-77 h-77 rounded-50" src="src/assets/categories/catalogues.webp" alt="Catalogues">
            <span>Catalogues</span>
        </div>
    </div>
    <div class="list w-full bg-white pl-5">
        <div class="actualités flex flex-row justify-between px-39">
            <p class="title pb-10 text-center font-700">Actualités et promotions</p>
            <img class="cross" src="src/assets/svg/menu/x.svg">
        </div>
        <div class="actualité flex flex-row justify-between px-39 py-9 gap-2">
            <div class="flex flex-row gap-6">
                <img class="icon w-23 rounded-30" src="src/assets/icons/menu/catalogue.webp" alt="icon">
                <p class="text">Catalogues</p>
            </div>
        </div>
        <div
            class="actualité flex flex-row justify-between px-39 py-9 gap-2 bg-menu-promotion-red-background rounded-5">
            <div class="flex flex-row gap-6">
                <img class="icon w-23 rounded-30" src="src/assets/icons/menu/promotion.webp" alt="icon">
                <p class="text">Promotions</p>
            </div>
            <img class="arrow" src="src/assets/svg/menu/arrow-red.svg">
        </div>
        <div class="actualité flex flex-row justify-between px-39 py-9 gap-2">
            <div class="flex flex-row gap-6">
                <img class="icon w-23 rounded-30" src="src/assets/icons/menu/mois-online.webp" alt="icon">
                <p class="text">Mois Online jusqu’à 70% d’écos</p>
            </div>
        </div>
        <div class="actualité flex flex-row justify-between px-39 py-9 gap-2">
            <div class="flex flex-row gap-6">
                <img class="icon w-23 rounded-30" src="src/assets/icons/menu/marque-picto.webp" alt="icon">
                <p class="text">-60% sur le 2ème - Old El Paso</p>
            </div>
        </div>
        <div class="actualité flex flex-row justify-between px-39 py-9 gap-2">
            <div class="flex flex-row gap-6">
                <img class="icon w-23 rounded-30" src="src/assets/icons/menu/promotion.webp" alt="icon">
                <p class="text">Le Petit Marseillais</p>
            </div>
        </div>
    </div>
</div>