<section class="marques w-screen h-fit py-10">
    <div class="layout flex flex-col md:flex-row justify-center items-center gap-20">
        <img class="img w-302 h-auto mx-auto md:mx-0" src="src/assets/marques/animalerie.webp" alt="animalerie">
        <img class="img w-302 h-auto mx-auto md:mx-0" src="src/assets/marques/traiteur.webp" alt="traiteur">
        <img class="img w-302 h-auto mx-auto md:mx-0" src="src/assets/marques/macave.webp" alt="macave">
        <img class="img w-302 h-auto mx-auto md:mx-0" src="src/assets/marques/voyage.webp" alt="voyage">
    </div>
</section>