<section class="actions w-screen bg-accueil-very-pale-blue px-30 md:px-0">
    <div class="flex flex-col md:flex-row justify-center py-40 md:py-20 gap-10 md:gap-100">
        <div class="element flex flex-row w-fit justify-center items-center px-7 py-4 gap-27">
            <img class="icon" src="src/assets/actions/magasin.svg" alt="magasin">
            <p class='text text-nav-blue hover:text-nav-blue-hover font-700'>Trouvez un magasin</p>
        </div>
        <div class="element flex flex-row w-fit justify-center items-center px-7 py-4 gap-27">
            <img class="icon" src="src/assets/actions/aide.svg" alt="aide">
            <p class='text text-nav-blue hover:text-nav-blue-hover font-700'>Obtenir de l'aide</p>
        </div>
        <div class="element flex flex-row w-fit justify-center items-center  px-7 py-4 gap-27">
            <img class="icon" src="src/assets/actions/app.svg" alt="app">
            <p class='text text-nav-blue hover:text-nav-blue-hover font-700'>Télécharger l'application</p>
        </div>
        <div class="element flex flex-row w-fit justify-center items-center px-7 py-4 gap-27">
            <img class="icon" src="src/assets/actions/faq.svg" alt="faq">
            <p class='text text-nav-blue hover:text-nav-blue-hover font-700'>Consulter le FAQ</p>
        </div>
    </div>
</section>