<section class="creerprofil w-screen md:w-[564px] flex flex-col justify-center p-32 md:mx-auto">

    <div class="top w-full flex flex-rox justify-between items-center py-10">
        <a class="btn-white flex flex-row gap-10" href="#"><img class="icon" src="src/assets/svg/creerprofil/arrow-back.svg" alt="arrow-back">Retour au site</a>
        <img class="logo w-[120px] h-[20px]" src="src/assets/logo/logo-line.svg" alt="logo">
    </div>

    <p class="title pb-20 text-center text-20 font-700 text-nav-blue mx-auto">Content de vous (re)voir !</p>

    <form class="form grid grid-cols-1 grid-rows-3 gap-30">
        <input class="input row-span-1" type="email" id="mail" name="mail" placeholder="E-mail *" required>
        <input class="input row-span-1" type="password" id="mdp" name="mdp" placeholder="Mot de passe *" required>
        <button type="submit" class="btn-blue w-fit row-span-1 justify-self-center">Me connecter</button>
    </form>

    <div class="pas-compte flex flex-col justify-center items-center py-30">
        <p class="text text-16 text-panier-grey font-600">Pas encore de compte Carrefour ?</p>
        <a href="#" class="btn-white">Inscrivez-vous</a>
    </div>

</section>